### ISSUE TITLE
deprecated methods from lh-vim-lib

### ISSUE THREAD

**Issue by dc-avasilev** [LucHermitte/lh-brackets#13]
~/.vim/plugged/lh-brackets/after/ftplugin/c/c_brackets.vim:98
~/.vim/plugged/lh-brackets/plugin/common_brackets.vim:199

fix plz
change #dev# to #ft#

**Comment by LucHermitte** [comment]
Sorry, it was fixed in the branch I've been testing for too long in the commits fc98098c9add6f635bcd841cab0031e4a3781750 and d04949bfe9d362ee85a2f0cb8bba68debfd5a76a

If you update lh-brackets you shouldn't be annoyed anymore.
