### ISSUE TITLE
E705: Variable name conflicts with an existing function: Close

### ISSUE THREAD

**Issue by dc-avasilev** [LucHermitte/lh-brackets#16]
Обнаружена ошибка при обработке function lh#brackets#define[3]..<SNR>209_DecodeDefineOptions:
строка   37:
E705: Имя переменной конфликтует с существующей функцией: Close

-----

An error was encountered while processing function lh # brackets # define [3] .. <SNR> 209_DecodeDefineOptions:
line 37:
E705: Variable name conflicts with an existing function: Close

-----

I think conflict with ctrlp.vim plugin, when try open php files, maybe I'm wrong

**Comment by LucHermitte** [comment]
Thanks for the bug report.
It should be fixed now.

In you want to know which plugin is still using global functions (instead of script-local or autoloaded functions), you can type `:verbose function Close`
