### ISSUE TITLE
Disable normal mode default bracket mappings

### ISSUE THREAD

**Issue by skitimoon** [LucHermitte/lh-brackets#17]
I want to use the default vim key mappings in normal mode.
But I cannot find a way to disable only some specific keymap (`(`, `{`).
Only way to disable them is to disable all default mapping (`g:cb_no_default_brackets`).
Is there a way to disable only some specific default keymap?

**Comment by skitimoon** [comment]
Thanks for the update! It works as I expected. 👍

**Comment by LucHermitte** [comment]
Thanks.
