### ISSUE TITLE
Adding a semicolon before another semicolon or between two brackets throws an error with a C++ file

### ISSUE THREAD

**Issue by Ninjaclasher** [LucHermitte/lh-brackets#18]
When inserting a `;` before another `;` or between `()` in a C++ file, it throws this error:
```
Error detected while processing function lh#mapping#_switch[1]..lh#mapping#_switch_int:
line    3:
E117: Unknown function: s:JumpOverAllClose
Press ENTER or type command to continue
```
Also, a `-1` is inserted where the `;` would have been after Enter is pressed.

**Comment by LucHermitte** [comment]
Sorry for the delay, I'm just back from holidays, it should be fixed now.
