### ISSUE TITLE
After installing the plugin, vim reports several errors, like 'lh#mapping#plug[34]..lh#mapping#define'

### ISSUE THREAD

**Issue by leonleon33156** [LucHermitte/lh-brackets#22]
After installing the plugins using vundle, vim reports several errors. 
The errors list as follows:
__****Error detected while processing function lh#mapping#plug[34]..lh#mapping#define
line    7:
E109: Missing ':' after '?'
E15: Invalid expression: get(a:md, 'expr', 0) ? "\<c-r>=".(a:md.rhs)."\<cr**>"**__

Any help would be appreciated.

**Comment by LucHermitte** [comment]
It should be fixed now. You'll need to update lh-vim-lib

Let me know if you're still experimenting this issue (or any others related to IMAP.vim/vim-latex)
