### ISSUE TITLE
Weird behaviour when there are an unequal amount of opening/closing braces.

### ISSUE THREAD

**Issue by Ninjaclasher** [LucHermitte/lh-brackets#26]
**Is your feature request related to a problem? Please describe.**
Suppose I had a C++ file:
```cpp
int main()
{
    if (...)
    {
        for (...)
        {
            if (...)
            {
             <cursor here>   
        }
    }
}
```
(Notice the missing closing bracket).  Currently, there is no easy way to insert a closing bracket at `<cursor here>`, as attempting to type a `}` will jump to the next bracket, rather than insert a new one. I've been unable to find anything in the documentation to deal with a situation like this.

**Describe the solution you'd like**
A new bracket is inserted rather than jump to the next bracket when there is a bracket mismatch (or perhaps a manual toggle if this is too computational expensive).

**Describe alternatives you've considered**
One way I've currently been dealing with this situation is by following the jumps to the end, in which case a new bracket would be inserted, and then moving the bracket up to the place where it should be. However, this is suboptimal, as it can become a hassle when nested very deeply.

**Additional context**
None.

**Comment by LucHermitte** [comment]
This is a consequence of 2b30ded693e72f003772aa626161e0b09b018d08, which relates to #23.

I'll add an option to permit to choose the preferred behaviour.

Do you prefer the behaviour if you locally override the C++ definitions with

     :Brackets { } -default -visual=0 -insert=1
        \ -open=function('lh#cpp#brackets#curly_open')

?

PS: it's always possible to neutralize what's happening with `CTRL-V`+`}`

**Comment by Ninjaclasher** [comment]
Yes, the behaviour your specified would be a great as an option. Thank you so much!

Also, I did not realize that `Ctrl-V` + `}` worked, thanks for the insight!

**Comment by LucHermitte** [comment]
If you set `g:cb_jump_over_newlines` to 0 in your `.vimrc`, this should revert to the old behaviour.

**Comment by Ninjaclasher** [comment]
Yup, saw your commit! Thanks for the quick implementation :)
