### ISSUE TITLE
cd_disable_default disables additional brackets

### ISSUE THREAD

**Issue by baileywickham** [LucHermitte/lh-brackets#27]
**Description**
cb_disable_default disables additional brackets. After adding the line below, double quote completion and paren completion are disabled even though they are not explicitly disabled. 
**To Reproduce**
1. Add ` let g:cb_disable_default = { '[': 'n', '{': 'nv' }` to `.vimrc`
2. Open a new file and hit `(`
3. `[, {` completion are still enabled. 

**Expected behavior**
Hitting `(` should close to `( )<++>`

I am trying to disable automatically closing single quotes.  From reading the docs I would expect `let g:cb_disable_default = { '''': 'i'}` to disable single quotes but leave everything else the same as the default behavior, am I missing something?

**Version**
NVIM v0.5.0-718-g090551a80

**Comment by LucHermitte** [comment]
Indeed, there was a mismatch in the handling and `g:cb_enable_default`  and `g:cb_disable_default`. 
Thanks for the report.

This should be fixed now.

**Comment by baileywickham** [comment]
Tested, it works as expected now. Thanks!
