### ISSUE TITLE
Please don't define mappings beginning with '!'

### ISSUE THREAD

**Issue by kmaglione** [LucHermitte/lh-brackets#4]
This leads to strange behavior when typing '!' in normal usage, and vim is trying to decide whether a mapping applies. These mappings are clearly not intended to be typed by a user, so please use <Plug> mappings instead.

**Comment by LucHermitte** [comment]
Yes. You're right. These mappings are historical: they were here long before `<Plug>` mappings came into existence.
I'll see to neutralize them.

**Comment by kmaglione** [comment]
Thanks
