### ISSUE TITLE
E15 and E116 when trying to type double brackets

### ISSUE THREAD

**Issue by Nemo1369** [LucHermitte/lh-brackets#8]
Installing lh-brackets with dependencies to MacVim ("mvim --version" here: http://pastebin.com/Jp4gnp38) (.vimrc here: http://pastebin.com/SXJxpMWy) leads to unavailability to type double brackets in a file of any type with message:

**E116: Invalid arguments for function lh#brackets#opener('"',0,"",function('lh#vim#brackets#dquotes'),""",1,'')
E15: Invalid expression: lh#brackets#opener('"',0,"",function('lh#vim#brackets#dquotes'),""",1,'')**

**Comment by LucHermitte** [comment]
Sorry, I still don't have enough tests for all these old features.

Let me know if you encounter any other issues.
